### ISSUE TITLE
Mount a host directory as a data volume in Docker

### ISSUE THREAD

**Issue by lvarayut** [meanjs/mean#1053]
Should we mount a host directory as a data volume in `docker-compose.yml`? So, we could develop on our local machine, and keep our codes sync between the local machine and a docker machine? As following:

```yml
web:
  build: .
  links:
   - db
  ports:
   - "3000:3000"
  environment: 
   NODE_ENV: development
  volumes:
    - .:/home/mean
db:
  image: mongo
  ports: 
   - "27017:27017"
```
