### ISSUE TITLE
rename docker-compose containers

### ISSUE THREAD

**Issue by soupman99** [meanjs/mean#1331]
Is there a way to rename my containers via docker-compose.yml?  I tried renaming my db but my meanjs isn't able to find the renamed container.

**Comment by lirantal** [comment]
Check the code for the latest commit on master, you can rename/override it in docker-compose.yml

**Comment by soupman99** [comment]
Yeah I tried that but still having issues.  Here's my db config.
```
db:
  image: mongo:3.2
  container_name: mydb
  restart: always
  ports:
   - "27017:27017"
  volumes:
   - db:/data/db
```
Then I'm running `docker-compose up` but my meanjs container can't connect to the renamed db container.
