### ISSUE TITLE
custom network connection error

### ISSUE THREAD

**Issue by soupman99** [meanjs/mean#1379]
I'm running [nginx-proxy](https://github.com/jwilder/nginx-proxy) to automatically config a reverse proxy.

One requirement is defining a network for each service. 

```
web:
  restart: always
  build: .
  container_name: mysite
  command: npm start
  links:
   - db
  ports:
   - "3000:3000"
   - "5858:5858"
   - "35729:35729"
  environment:
   - NODE_ENV=development
   - VIRTUAL_HOST=mysite.local
  volumes:
   - ./:/opt/mean.js
   - /opt/mean.js/node_modules
   - /opt/mean.js/public
   - /opt/mean.js/uploads
  net: my_network

db:
  image: mongo:3.2
  container_name: mysite_db
  restart: always
  ports:
   - "27017:27017"
  volumes:
   - db:/data/db
  net: my_network

```

The problem comes when my web container isn't able to connect to my db container.
`Could not connect to MongoDB!`
 What am I missing?
