### ISSUE TITLE
travis.yml errors on build 

### ISSUE THREAD

**Issue by thiagosoeiro** [meanjs/mean#1738]
Hi, I'm getting several errors when trying to build my project with travis.yml file generated by yeoman . This is the file below. Should it work by default or do I have to make any changes?

```
language: node_js
sudo: false
node_js:
  - 0.10
  - 0.12
  - 4
  - 5
# NodeJS v4 requires gcc 4.8
env:
  - NODE_ENV=travis CXX="g++-4.8" CC="gcc-4.8"
matrix:
  allow_failures:
    - node_js: 5
services:
  - mongodb
# gcc 4.8 requires ubuntu-toolchain-r-test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
    - clang
before_install:
  - gem update --system
  - gem install sass --version "=3.3.7"
  - npm i nsp -g
  - npm install protractor
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'node_modules/protractor/bin/webdriver-manager update --standalone --firefox'
  - 'node_modules/protractor/bin/webdriver-manager start 2>&1 &'
  - sleep 3
after_script:
  - nsp audit-package
  - grunt coverage
notifications:
  webhooks:
    urls:
      - $GITTER_IM_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
```

These are the errors:

https://ibb.co/k65pdv
https://ibb.co/kLy9dv

What's the problem here? Can you guys help me?
